### ISSUE TITLE
显示异常问题求助

### ISSUE THREAD

**Issue by drewzhang** [jl15988/joplin-plugin-code-perfect#3]
Copy Copied

1
2
3
4
5
Copy Copied
打开插件后，在富文本显示器里面，code模块下面显示这样子的内容。无法正常使用
![image](https://github.com/jl15988/joplin-plugin-code-perfect/assets/18046001/4402836a-906a-41b3-a2e9-69c7cdb105bb)

**Comment by jl15988** [comment]
已知晓该问题 #4

**Comment by jl15988** [comment]
v1.0.3版本已解决
