### ISSUE TITLE
Weird behaviour with the plugin

### ISSUE THREAD

**Issue by SourceE1** [jl15988/joplin-plugin-code-perfect#4]
Whenever I try to add a code block and paste some bash script in, I get this weird result where the numbered lines and some text "copy" and "copied" are outside the box:
<img width="290" alt="Screenshot 2024-07-03 at 09 56 13" src="https://github.com/jl15988/joplin-plugin-code-perfect/assets/174606497/f6aaf29c-c36d-477f-83a4-71b3b0f52fad">
I am very new to Joplin so may be a user error.
I have these other plugins installed:
<img width="1026" alt="Screenshot 2024-07-03 at 12 38 35" src="https://github.com/jl15988/joplin-plugin-code-perfect/assets/174606497/943bfe4f-7bf8-454c-bc83-0c0a4985fc44">

**Comment by SourceE1** [comment]
Leaving the note and coming back to it, it now looks like this:
<img width="194" alt="Screenshot 2024-07-03 at 12 48 18" src="https://github.com/jl15988/joplin-plugin-code-perfect/assets/174606497/8ca56f47-1769-48e2-8d4c-016f91495afc">

**Comment by drewzhang** [comment]
我也是同样的问题，这个插件很好用，跪求处理这个bug

**Comment by jl15988** [comment]
After testing, it was found that this plugin is not compatible with rich text editing, only with Markdown. The original intention of this plugin was to make my own documents look better, but it unexpectedly gained favor from some people. If possible, I will do my best to fix this problem.

**Comment by Bangkokian** [comment]
Yeah, same issue. I'm getting a bulleted list of numbers following the code block. 

And as @SourceE1  noted, returning to the note reveals the code block is gone.
